### ISSUE TITLE
Error when trying to use primary macro

### ISSUE THREAD

**Issue by sdogruyol** [waterlink/postgres_adapter.cr#1]
When i try to assign primary key like below

``` crystal
require "active_record"
require "postgres_adapter"

ENV["PG_URL"] = "postgres://serdardogruyol@localhost:5432/kiosk"

class User < ActiveRecord::Model
  adapter postgres

  primary(id :: Int32)

end

```

I get a macro expand error like this

```
Error in macro 'primary' /Users/serdardogruyol/serdar/pg-sample/libs/active_record/model.cr:86, line 2:

  1.       @@primary_field = "id"
  2.       field id :: Int32
  3.       _field primary_key, id :: Int32
  4.

      field id :: Int32
      ^~~~~

```

**Comment by waterlink** [comment]
I will take a look into that a bit later today if you haven't figured out yet the problem

**Comment by sdogruyol** [comment]
@waterlink i figured it out. If you dont specify the name of the model this happens

**Comment by waterlink** [comment]
Ah, yes, exactly. I think the name of the model is mandatory (it initializes your model class state). Unless I can find a nice workaround for it. Let me play a bit in carc.in.

**Comment by waterlink** [comment]
Oh I see. This can be done automagically with `macro inherited`. Let me try to do it in `active_record`.

**Comment by waterlink** [comment]
@sdogruyol PR for a fix in the upstream: https://github.com/waterlink/active_record.cr/pull/21 - can you take a look?
