### ISSUE TITLE
crystal v0.18 support

### ISSUE THREAD

**Issue by fridgerator** [waterlink/postgres_adapter.cr#9]
I am just curious if there was currently a workaround to use postgres with active_record.cr + crystal v0.18.7.  It seems most of the problems come from the [Segfault: using generics](https://github.com/crystal-lang/crystal/issues/1408) issue in the crystal repo.

**Comment by waterlink** [comment]
There is one solution in flight. It is mostly done. Probably by Sunday
there should be an update.
Nick Franken notifications@github.com schrieb am Fr., 22. Juli 2016 um
9:24 PM:

**Comment by fridgerator** [comment]
👍

**Comment by waterlink** [comment]
New version has been released (both `active_record.cr` and `postgres_adapter.cr`). It works with latest version of Crystal. If you could try it out on your project(s) would be awesome!

**Comment by fridgerator** [comment]
Its working great!  Thanks!
